### ISSUE TITLE
Throwing type error when generating manifest

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-oss-cli#21]
## Description
When trying to generate a new third party manifest file, the CLI throws and error and exits.

## Steps to Reproduce
1. Clone https://github.com/newrelic/instant-observability-website
2. Install your dependencies using `yarn install`
3. Attempt to generate the manifest file with `oss third-party manifest`
4. Notice that the generated `third_party_manifest.json` file does not contain and of the dependencies

## Expected Behaviour
A full manifest file is generated.

## Relevant Logs / Console output

<img width="1500" alt="Screen Shot 2022-03-03 at 11 27 13 AM" src="https://user-images.githubusercontent.com/70179303/156638278-7efdd2ae-c123-4748-a04e-df58a8816f56.png">

## Your Environment

* OSS CLI version used: @newrelic/newrelic-oss-cli/0.1.2 darwin-x64 node-v16.12.0
* Browser name and version: N/A
* Operating System and version: MacOS V12.2.1

**Comment by jpvajda** [comment]
relates to this issue: https://github.com/newrelic/instant-observability-website/issues/52

**Comment by bizob2828** [comment]
I  was asked to look at this since I was the last to fix things in the project.  This appears to be an issue with one of the dependencies in the instant-observability-website: `use-mobile-detect-hook`.  This tool assumes every dependency has `repository.url` in their package.json.  I'm not sure the requirements for oss third party but it's treating it as something that is absolutely necessary.  I recommend opening a PR with the `use-mobile-detect-hook` repo to include this, or remove this dependency?   This is where it is failing in the tool: https://github.com/newrelic/newrelic-oss-cli/blob/master/packages/newrelic-plugin-oss-third-party/src/commands/third-party.js#L204

**Comment by aswanson-nr** [comment]
Thanks to @bizob2828 sleuthing, we know this is an issue with one of our packages and not with the CLI itself. I'm going to close this issue.

**Comment by jpvajda** [comment]
The related PR for use-mobile-detect-hook was merged in, @aswanson-nr will that resolve this issue now?
